# Generated by Django 2.0 on 2018-11-30 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('idintegrante', models.AutoField(db_column='IDINTEGRANTE', primary_key=True, serialize=False)),
                ('color', models.CharField(db_column='COLOR', max_length=100)),
                ('numeromensaje', models.CharField(db_column='NUMEROMENSAJE', max_length=100)),
                ('muere', models.IntegerField(db_column='MUERE', default=0)),
            ],
            options={
                'db_table': 'INTEGRANTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('idmesa', models.AutoField(db_column='IDMESA', primary_key=True, serialize=False)),
                ('integrantes', models.IntegerField(db_column='INTEGRANTES')),
                ('valoracobra', models.DecimalField(db_column='VALORACOBRA', decimal_places=20, max_digits=50)),
                ('fechacobro', models.DateField(db_column='FECHACOBRO', null=True)),
                ('muere', models.IntegerField(db_column='MUERE', default=0)),
            ],
            options={
                'db_table': 'MESA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='IDPERSONA', primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_column='CEDULA', max_length=10, null=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, null=True)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=100)),
                ('tefefono', models.CharField(db_column='TELEFONO', max_length=100)),
            ],
            options={
                'db_table': 'PERSONA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Retejida',
            fields=[
                ('idretejida', models.AutoField(db_column='IDRETEJIDA', primary_key=True, serialize=False)),
                ('valoracobro', models.DecimalField(db_column='VALORACOBRO', decimal_places=20, max_digits=50)),
                ('fechapago', models.DateField(db_column='FECHAPAGO')),
                ('fechacobro', models.DateField(db_column='FECHACOBRO', null=True)),
                ('mesa', models.ForeignKey(db_column='MESACOBRO', on_delete=django.db.models.deletion.DO_NOTHING, to='mesas.Mesa')),
            ],
            options={
                'db_table': 'RETEJIDA',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='personaacobrar',
            field=models.ForeignKey(db_column='PERSONAACOBRAR', on_delete=django.db.models.deletion.DO_NOTHING, to='mesas.Persona'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='mesa',
            field=models.ForeignKey(db_column='MESAPERTENECE', on_delete=django.db.models.deletion.DO_NOTHING, to='mesas.Mesa'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='persona',
            field=models.ForeignKey(db_column='PERSONAINTEGRANTE', on_delete=django.db.models.deletion.DO_NOTHING, to='mesas.Persona'),
        ),
    ]
