# Generated by Django 2.0 on 2018-11-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='integrantes',
        ),
        migrations.AddField(
            model_name='mesa',
            name='numerointegrantes',
            field=models.IntegerField(db_column='NUMEROINTEGRANTES', default=0),
        ),
    ]
