# Generated by Django 2.0 on 2018-11-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_auto_20181130_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='fechacobro',
            field=models.DateField(blank=True, db_column='FECHACOBRO', null=True),
        ),
    ]
