# Generated by Django 2.0 on 2018-11-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_auto_20181130_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(blank=True, db_column='CEDULA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(blank=True, db_column='NOMBRE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retejida',
            name='fechacobro',
            field=models.DateField(blank=True, db_column='FECHACOBRO', null=True),
        ),
    ]
